[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Gunix Framework"
authors = [{name = "Nubitic", email = "contacto@nubitic.mx"}]
dynamic = ["version", "description"]
